### ISSUE TITLE
Whatsapp Business Support

### ISSUE THREAD

**Issue by zek** [ben221199/WAPI#20]
Hello,

Is your repo support whatsapp business?

I'm trying to contact with you. Please contact with me drtzack@gmail.com

**Comment by ben221199** [comment]
WAPI is the basis for implementing an application for both WhatsApp and WhatsApp Business. It provides classes to register an account and to connect to the FunXMPP server (including encrypting/decrypting and encoding/decoding). E2E, messaging and most other things are not implemented, because that is the responsibility of the user of this library.
